-- ============================================================
--  TBC_ID_CATALOG.lua
--  Auto-generated reference data for The Burning Crusade zone music IDs.
--  Source: wowdev/wow-listfile community-listfile-withcapitals.csv
--  Release: 202603051942
--  Generated UTC: 2026-03-05T23:01:10Z
--  Note: This file is for catalog/config authoring and is not loaded by the addon runtime yet.
-- ============================================================

BElfVR_TBCIDCatalogMeta = {
    source = "wowdev/wow-listfile",
    release = "202603051942",
    generatedUTC = "2026-03-05T23:01:10Z",
    scope = "TBC-era zone music catalogs (Quel'Thalas focus + Outland + key TBC instances)",
}

BElfVR_TBCZoneMusicCatalog = {
    quelthalas = {
        eversong = {
            { id = 53458, path = "Sound/music/ZONEMUSIC/Eversong/ES_BuildingWalkDay01.mp3" },
            { id = 53459, path = "Sound/music/ZONEMUSIC/Eversong/ES_BuildingWalkDay02.mp3" },
            { id = 53460, path = "Sound/music/ZONEMUSIC/Eversong/ES_BuildingWalkNight01.mp3" },
            { id = 53461, path = "Sound/music/ZONEMUSIC/Eversong/ES_BuildingWalkNight02.mp3" },
            { id = 53462, path = "Sound/music/ZONEMUSIC/Eversong/ES_RuinsWalkDay01.mp3" },
            { id = 53463, path = "Sound/music/ZONEMUSIC/Eversong/ES_RuinsWalkDay02.mp3" },
            { id = 53464, path = "Sound/music/ZONEMUSIC/Eversong/ES_RuinsWalkDay03.mp3" },
            { id = 53465, path = "Sound/music/ZONEMUSIC/Eversong/ES_RuinsWalkNight01.mp3" },
            { id = 53466, path = "Sound/music/ZONEMUSIC/Eversong/ES_RuinsWalkNight02.mp3" },
            { id = 53467, path = "Sound/music/ZONEMUSIC/Eversong/ES_RuinsWalkNight03.mp3" },
            { id = 53468, path = "Sound/music/ZONEMUSIC/Eversong/ES_ScenicIntroNight01.mp3" },
            { id = 53469, path = "Sound/music/ZONEMUSIC/Eversong/ES_ScortchedWalkDay01.mp3" },
            { id = 53470, path = "Sound/music/ZONEMUSIC/Eversong/ES_ScortchedWalkDay02.mp3" },
            { id = 53471, path = "Sound/music/ZONEMUSIC/Eversong/ES_ScortchedWalkNight01.mp3" },
            { id = 53472, path = "Sound/music/ZONEMUSIC/Eversong/ES_ScortchedWalkNight02.mp3" },
            { id = 53473, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonIntro01.mp3" },
            { id = 53474, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonWalkDay01.mp3" },
            { id = 53475, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonWalkDay02.mp3" },
            { id = 53476, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonWalkDay03.mp3" },
            { id = 53477, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonWalkNight01.mp3" },
            { id = 53478, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonWalkNight02.mp3" },
            { id = 53479, path = "Sound/music/ZONEMUSIC/Eversong/ES_SilvermoonWalkNight03.mp3" },
            { id = 53480, path = "Sound/music/ZONEMUSIC/Eversong/ES_SunstriderWalkDay01.mp3" },
            { id = 53481, path = "Sound/music/ZONEMUSIC/Eversong/ES_SunstriderWalkDay02.mp3" },
            { id = 53482, path = "Sound/music/ZONEMUSIC/Eversong/ES_SunstriderWalkDay03.mp3" },
            { id = 53483, path = "Sound/music/ZONEMUSIC/Eversong/ES_SunstriderWalkNight01.mp3" },
            { id = 53484, path = "Sound/music/ZONEMUSIC/Eversong/ES_SunstriderWalkNight02.mp3" },
            { id = 53485, path = "Sound/music/ZONEMUSIC/Eversong/ES_SunstriderWalkNight03.mp3" },
        },
        ghostlands = {
            { id = 53499, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_EversongDarkWalkUni01.mp3" },
            { id = 53500, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_EversongDarkWalkUni02.mp3" },
            { id = 53501, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_EversongDarkWalkUni03.mp3" },
            { id = 53502, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_EversongDarkWalkUni04.mp3" },
            { id = 53503, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest1WalkDay01.mp3" },
            { id = 53504, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest1WalkDay02.mp3" },
            { id = 53505, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest1WalkNight01.mp3" },
            { id = 53506, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest2WalkDay01.mp3" },
            { id = 53507, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest2WalkNight01.mp3" },
            { id = 53508, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest2WalkNight02.mp3" },
            { id = 53509, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest3WalkDay01.mp3" },
            { id = 53510, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest3WalkNight01.mp3" },
            { id = 53511, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest3WalkNight02.mp3" },
            { id = 53512, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_Forest3WalkNight03.mp3" },
            { id = 53513, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_ScenicWalkUni01.mp3" },
            { id = 53514, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_ScenicWalkUni02.mp3" },
            { id = 53515, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_ScenicWalkUni03.mp3" },
            { id = 53516, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_ShalandisWalkUni01.mp3" },
            { id = 53517, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_ShalandisWalkUni02.mp3" },
            { id = 53518, path = "Sound/music/ZONEMUSIC/Ghostlands/GL_ShalandisWalkUni03.mp3" },
        },
        zulaman = {
            { id = 53825, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_AMB10.mp3" },
            { id = 53826, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_AMB11.mp3" },
            { id = 53827, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_AMB12.mp3" },
            { id = 53828, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_AMB13.mp3" },
            { id = 53829, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_AMB14.mp3" },
            { id = 53830, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_AMB15.mp3" },
            { id = 53831, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_BTL11.mp3" },
            { id = 53832, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_BTL12.mp3" },
            { id = 53833, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_BTL13.mp3" },
            { id = 53834, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_BTL14.mp3" },
            { id = 53835, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_BTL15.mp3" },
            { id = 53836, path = "Sound/music/ZONEMUSIC/Zulaman/ZA_zulaman_VCT10.mp3" },
        },
        sunwell = {
            { id = 53700, path = "Sound/music/ZONEMUSIC/Sunwell/SW_AssemblyChamberWalkUni01.mp3" },
            { id = 53701, path = "Sound/music/ZONEMUSIC/Sunwell/SW_AssemblyChamberWalkUni02.mp3" },
            { id = 53702, path = "Sound/music/ZONEMUSIC/Sunwell/SW_FelEnergyWalkUni01.mp3" },
            { id = 53703, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleDarkWalkUni01.mp3" },
            { id = 53704, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleDarkWalkUni02.mp3" },
            { id = 53705, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleDarkWalkUni03.mp3" },
            { id = 53706, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleLightWalkUni01.mp3" },
            { id = 53707, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleLightWalkUni02.mp3" },
            { id = 53708, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleLightWalkUni03.mp3" },
            { id = 53709, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleMedWalkUni01.mp3" },
            { id = 53710, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleMedWalkUni02.mp3" },
            { id = 53711, path = "Sound/music/ZONEMUSIC/Sunwell/SW_IsleMedWalkUni03.mp3" },
            { id = 53712, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersArrivalWalkUni01.mp3" },
            { id = 53713, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersAsylumWalkUni01.mp3" },
            { id = 53714, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersAsylumWalkUni02.mp3" },
            { id = 53715, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersAsylumWalkUni03.mp3" },
            { id = 53716, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersTerraceWalkUni01.mp3" },
            { id = 53717, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersTerraceWalkUni02.mp3" },
            { id = 53718, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersTerraceWalkUni03.mp3" },
            { id = 53719, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersTerraceWalkUni04.mp3" },
            { id = 53720, path = "Sound/music/ZONEMUSIC/Sunwell/SW_MagistersTerraceWalkUni05.mp3" },
            { id = 53721, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellArrivalWalkUni01.mp3" },
            { id = 53722, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellWalkUni01.mp3" },
            { id = 53723, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellWalkUni02.mp3" },
            { id = 53724, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellWalkUni03.mp3" },
            { id = 53725, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellWalkUni04.mp3" },
            { id = 53726, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellWalkUni05.mp3" },
            { id = 53727, path = "Sound/music/ZONEMUSIC/Sunwell/SW_PlateauSunwellWalkUni06.mp3" },
            { id = 53728, path = "Sound/music/ZONEMUSIC/Sunwell/SW_QuelDanasWalkUni01.mp3" },
            { id = 53729, path = "Sound/music/ZONEMUSIC/Sunwell/SW_QuelDanasWalkUni02.mp3" },
            { id = 53730, path = "Sound/music/ZONEMUSIC/Sunwell/SW_SanctumWalkUni01.mp3" },
            { id = 53731, path = "Sound/music/ZONEMUSIC/Sunwell/SW_ShorelAranWalkUni01.mp3" },
            { id = 53732, path = "Sound/music/ZONEMUSIC/Sunwell/SW_SunwellBombingRunUni01.mp3" },
            { id = 53733, path = "Sound/music/ZONEMUSIC/Sunwell/SW_SunwellFlybyUni01.mp3" },
            { id = 53734, path = "Sound/music/ZONEMUSIC/Sunwell/SW_TheWellWalkUni01.mp3" },
            { id = 53735, path = "Sound/music/ZONEMUSIC/Sunwell/SW_TheWellWalkUni02.mp3" },
            { id = 53736, path = "Sound/music/ZONEMUSIC/Sunwell/SW_TheWellWalkUni03.mp3" },
        },
    },
    outland = {
        hellfire_peninsula = {
            { id = 53520, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/BL_HE_OgreWalkUni01.mp3" },
            { id = 53521, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/BL_HE_OgreWalkUni02.mp3" },
            { id = 53522, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_ArmouryIntroUni01.mp3" },
            { id = 53523, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_CitadelDemonWalkUni01.mp3" },
            { id = 53524, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_CitadelDemonWalkUni02.mp3" },
            { id = 53525, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_CitadelIntroUni01.mp3" },
            { id = 53526, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_GeneralWalkUni01.mp3" },
            { id = 53527, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_GeneralWalkUni02.mp3" },
            { id = 53528, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_GeneralWalkUni03.mp3" },
            { id = 53529, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_GeneralWalkUni04.mp3" },
            { id = 53530, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_GeneralWalkUni05.mp3" },
            { id = 53531, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_PathOfGloryIntroUni01.mp3" },
            { id = 53532, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_RampartsWalkUni01.mp3" },
            { id = 53533, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_RampartsWalkUni02.mp3" },
            { id = 53534, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_StairsIntroUni01.mp3" },
            { id = 53535, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_WistfulIntroUni01.mp3" },
            { id = 53536, path = "Sound/music/ZONEMUSIC/HellfirePeninsula/HE_WistfulIntroUni02.mp3" },
        },
        zangarmarsh = {
            { id = 53816, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_CoilfangWalkUni01.mp3" },
            { id = 53817, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_CoilfangWalkUni02.mp3" },
            { id = 53818, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_CoilfangWalkUni03.mp3" },
            { id = 53819, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_GeneralWalkUni01.mp3" },
            { id = 53820, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_GeneralWalkUni02.mp3" },
            { id = 53821, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_GeneralWalkUni03.mp3" },
            { id = 53822, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_GeneralWalkUni04.mp3" },
            { id = 53823, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_GeneralWalkUni05.mp3" },
            { id = 53824, path = "Sound/music/ZONEMUSIC/ZangarMarsh/ZA_GeneralWalkUni06.mp3" },
        },
        terokkar = {
            { id = 53796, path = "Sound/music/ZONEMUSIC/Terokkar/TF_AuchindounWalkUni01.mp3" },
            { id = 53797, path = "Sound/music/ZONEMUSIC/Terokkar/TF_AuchindounWalkUni02.mp3" },
            { id = 53798, path = "Sound/music/ZONEMUSIC/Terokkar/TF_AuchindounWalkUni03.mp3" },
            { id = 53799, path = "Sound/music/ZONEMUSIC/Terokkar/TF_BoneWalkUni01.mp3" },
            { id = 53800, path = "Sound/music/ZONEMUSIC/Terokkar/TF_BoneWalkUni02.mp3" },
            { id = 53801, path = "Sound/music/ZONEMUSIC/Terokkar/TF_BoneWalkUni03.mp3" },
            { id = 53802, path = "Sound/music/ZONEMUSIC/Terokkar/TF_BoneWalkUni04.mp3" },
            { id = 53803, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ForestWalkUni01.mp3" },
            { id = 53804, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ForestWalkUni02.mp3" },
            { id = 53805, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ForestWalkUni03.mp3" },
            { id = 53806, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ShattrathWalkUni01.mp3" },
            { id = 53807, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ShattrathWalkUni02.mp3" },
            { id = 53808, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ShattrathWalkUni03.mp3" },
            { id = 53809, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ShattrathWalkUni04.mp3" },
            { id = 53810, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ShattrathWalkUni05.mp3" },
            { id = 53811, path = "Sound/music/ZONEMUSIC/Terokkar/TF_ShattrathWalkUni06.mp3" },
        },
        nagrand = {
            { id = 53584, path = "Sound/music/ZONEMUSIC/Nagrand/NA_DiamondIntroUni01.mp3" },
            { id = 53585, path = "Sound/music/ZONEMUSIC/Nagrand/NA_GeneralWalkDay01.mp3" },
            { id = 53586, path = "Sound/music/ZONEMUSIC/Nagrand/NA_GeneralWalkDay02.mp3" },
            { id = 53587, path = "Sound/music/ZONEMUSIC/Nagrand/NA_GeneralWalkDay03.mp3" },
            { id = 53588, path = "Sound/music/ZONEMUSIC/Nagrand/NA_GeneralWalkNight01.mp3" },
            { id = 53589, path = "Sound/music/ZONEMUSIC/Nagrand/NA_GeneralWalkNight02.mp3" },
            { id = 53590, path = "Sound/music/ZONEMUSIC/Nagrand/NA_GeneralWalkNight03.mp3" },
        },
        blades_edge = {
            { id = 53350, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_DryForestWalkUni01.mp3" },
            { id = 53351, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_DryForestWalkUni02.mp3" },
            { id = 53352, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_DryForestWalkUni03.mp3" },
            { id = 53353, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_GeneralWalkUni01.mp3" },
            { id = 53354, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_GeneralWalkUni02.mp3" },
            { id = 53355, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_GeneralWalkUni03.mp3" },
            { id = 53356, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_GeneralWalkUni04.mp3" },
            { id = 53357, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_GeneralWalkUni05.mp3" },
            { id = 53358, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_OgreWalkUni01.mp3" },
            { id = 53359, path = "Sound/music/ZONEMUSIC/BladesEdge/BL_OgreWalkUni02.mp3" },
        },
        netherstorm = {
            { id = 53620, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni01.mp3" },
            { id = 53621, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni02.mp3" },
            { id = 53622, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni03.mp3" },
            { id = 53623, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni04.mp3" },
            { id = 53624, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni05.mp3" },
            { id = 53625, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni06.mp3" },
            { id = 53626, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni07.mp3" },
            { id = 53627, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni08.mp3" },
            { id = 53628, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni09.mp3" },
            { id = 53629, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_GeneralWalkUni10.mp3" },
            { id = 53630, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_MushroomIntroUni01.mp3" },
            { id = 53631, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_MushroomIntroUni02.mp3" },
            { id = 53632, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_MushroomIntroUni03.mp3" },
            { id = 53633, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_NetherplantIntroUni01.mp3" },
            { id = 53634, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_NetherplantIntroUni02.mp3" },
            { id = 53635, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_NetherplantIntroUni03.mp3" },
            { id = 53636, path = "Sound/music/ZONEMUSIC/Netherstorm/NS_NetherplantIntroUni04.mp3" },
        },
        shadowmoon_valley = {
            { id = 53689, path = "Sound/music/ZONEMUSIC/ShadowmoonValley/SV_GeneralWalkUni01.mp3" },
            { id = 53690, path = "Sound/music/ZONEMUSIC/ShadowmoonValley/SV_GeneralWalkUni02.mp3" },
            { id = 53691, path = "Sound/music/ZONEMUSIC/ShadowmoonValley/SV_GeneralWalkUni03.mp3" },
            { id = 53692, path = "Sound/music/ZONEMUSIC/ShadowmoonValley/SV_GeneralWalkUni04.mp3" },
            { id = 53693, path = "Sound/music/ZONEMUSIC/ShadowmoonValley/SV_GeneralWalkUni05.mp3" },
            { id = 53694, path = "Sound/music/ZONEMUSIC/ShadowmoonValley/SV_GeneralWalkUni06.mp3" },
        },
        outland_general = {
            { id = 53637, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_ActionWalkUni01.mp3" },
            { id = 53638, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_AllianceBaseWalkUni01.mp3" },
            { id = 53639, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_AllianceBaseWalkUni02.mp3" },
            { id = 53640, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_ArakkoaIntroUni01.mp3" },
            { id = 53641, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_ArakkoaIntroUni02.mp3" },
            { id = 53642, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_BloodElfBaseWalkUni01.mp3" },
            { id = 53643, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_BloodElfBaseWalkUni02.mp3" },
            { id = 53644, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_BurningLegionIntroUni01.mp3" },
            { id = 53645, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_BurningLegionIntroUni02.mp3" },
            { id = 53646, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CenarionIntroUni01.mp3" },
            { id = 53647, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CenarionIntroUni02.mp3" },
            { id = 53648, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CenarionIntroUni03.mp3" },
            { id = 53649, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt01.mp3" },
            { id = 53650, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt02.mp3" },
            { id = 53651, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt03.mp3" },
            { id = 53652, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt04.mp3" },
            { id = 53653, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt05.mp3" },
            { id = 53654, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt06.mp3" },
            { id = 53655, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_Corrupt07.mp3" },
            { id = 53656, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CorruptIntro.mp3" },
            { id = 53657, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CrystalIntroUni01.mp3" },
            { id = 53658, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CrystalIntroUni02.mp3" },
            { id = 53659, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_CrystalIntroUni03.mp3" },
            { id = 53660, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_DemonIntroUni01.mp3" },
            { id = 53661, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_DraeneiBaseWalkUni01.mp3" },
            { id = 53662, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_DraeneiBaseWalkUni02r.mp3" },
            { id = 53663, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_FelOrcIntroUni01.mp3" },
            { id = 53664, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_FelOrcIntroUni02.mp3" },
            { id = 53665, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_HistoricIntroUni01.mp3" },
            { id = 53666, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_HordeBaseWalkUni01.mp3" },
            { id = 53667, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_HordeBaseWalkUni02.mp3" },
            { id = 53668, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_HordeBaseWalkUni03.mp3" },
            { id = 53669, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_HordeBaseWalkUni04.mp3" },
            { id = 53670, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_IllidansArmyIntroUni01.mp3" },
            { id = 53671, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_OgreIntroUni01.mp3" },
            { id = 53672, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_OgreIntroUni02.mp3" },
            { id = 53673, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_OrcIntroUni01.mp3" },
            { id = 53674, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_OrcIntroUni02.mp3" },
            { id = 53675, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_OrcIntroUni03.mp3" },
            { id = 53676, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_OrcIntroUni04.mp3" },
            { id = 53677, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_ScenicIntroUni01.mp3" },
            { id = 53678, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_ShamanIntroUni01.mp3" },
            { id = 53679, path = "Sound/music/ZONEMUSIC/OutlandGeneral/OL_ShamanIntroUni02.mp3" },
        },
    },
    tbc_instances = {
        karazhan = {
            { id = 53547, path = "Sound/music/ZONEMUSIC/Karazhan/KA_BackstageWalkUni01.mp3" },
            { id = 53548, path = "Sound/music/ZONEMUSIC/Karazhan/KA_BackstageWalkUni02.mp3" },
            { id = 53549, path = "Sound/music/ZONEMUSIC/Karazhan/KA_FoyerIntroUni01.mp3" },
            { id = 53550, path = "Sound/music/ZONEMUSIC/Karazhan/KA_FoyerWalkUni01.mp3" },
            { id = 53551, path = "Sound/music/ZONEMUSIC/Karazhan/KA_FoyerWalkUni02.mp3" },
            { id = 53552, path = "Sound/music/ZONEMUSIC/Karazhan/KA_FoyerWalkUni03.mp3" },
            { id = 53553, path = "Sound/music/ZONEMUSIC/Karazhan/KA_FoyerWalkUni04.mp3" },
            { id = 53554, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni01.mp3" },
            { id = 53555, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni02.mp3" },
            { id = 53556, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni03.mp3" },
            { id = 53557, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni04.mp3" },
            { id = 53558, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni05.mp3" },
            { id = 53559, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni06.mp3" },
            { id = 53560, path = "Sound/music/ZONEMUSIC/Karazhan/KA_GeneralWalkUni07.mp3" },
            { id = 53561, path = "Sound/music/ZONEMUSIC/Karazhan/KA_LibraryWalkUni01.mp3" },
            { id = 53562, path = "Sound/music/ZONEMUSIC/Karazhan/KA_LibraryWalkUni02.mp3" },
            { id = 53563, path = "Sound/music/ZONEMUSIC/Karazhan/KA_LibraryWalkUni03.mp3" },
            { id = 53564, path = "Sound/music/ZONEMUSIC/Karazhan/KA_LibraryWalkUni04.mp3" },
            { id = 53565, path = "Sound/music/ZONEMUSIC/Karazhan/KA_MalchezarWalkUni01.mp3" },
            { id = 53566, path = "Sound/music/ZONEMUSIC/Karazhan/KA_MalchezarWalkUni02.mp3" },
            { id = 53567, path = "Sound/music/ZONEMUSIC/Karazhan/KA_MalchezarWalkUni03.mp3" },
            { id = 53568, path = "Sound/music/ZONEMUSIC/Karazhan/KA_OperaHarpsiWalkUni01.mp3" },
            { id = 53569, path = "Sound/music/ZONEMUSIC/Karazhan/KA_OperaOrganWalkUni01.mp3" },
            { id = 53570, path = "Sound/music/ZONEMUSIC/Karazhan/KA_StableIntroUni01.mp3" },
            { id = 53571, path = "Sound/music/ZONEMUSIC/Karazhan/KA_StableWalkUni01.mp3" },
            { id = 53572, path = "Sound/music/ZONEMUSIC/Karazhan/KA_StableWalkUni02.mp3" },
            { id = 53573, path = "Sound/music/ZONEMUSIC/Karazhan/KA_StableWalkUni03.mp3" },
            { id = 53574, path = "Sound/music/ZONEMUSIC/Karazhan/KA_TowerWalkUni01.mp3" },
            { id = 53575, path = "Sound/music/ZONEMUSIC/Karazhan/KA_TowerWalkUni02.mp3" },
            { id = 53576, path = "Sound/music/ZONEMUSIC/Karazhan/KA_TowerWalkUni03.mp3" },
        },
        tempest_keep = {
            { id = 53779, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_11.mp3" },
            { id = 53780, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_12.mp3" },
            { id = 53781, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_13.mp3" },
            { id = 53782, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_14.mp3" },
            { id = 53783, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_16.mp3" },
            { id = 53784, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_17.mp3" },
            { id = 53785, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_18.mp3" },
            { id = 53786, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_19.mp3" },
            { id = 53787, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_20.mp3" },
            { id = 53788, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_22.mp3" },
            { id = 53789, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_AMB_23.mp3" },
            { id = 53790, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_BTL10.mp3" },
            { id = 53791, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_BTL11.mp3" },
            { id = 53792, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_BTL13.mp3" },
            { id = 53793, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_STG14.mp3" },
            { id = 53794, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_STG15.mp3" },
            { id = 53795, path = "Sound/music/ZONEMUSIC/TempestKeep/tk_TempestKeep_STG16.mp3" },
        },
        black_temple = {
            { id = 53305, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ArrivalWalkHero01.mp3" },
            { id = 53306, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ArrivalWalkUni02.mp3" },
            { id = 53307, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ArrivalWalkUni03.mp3" },
            { id = 53308, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ArrivalWalkUni04.mp3" },
            { id = 53309, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkHero09.mp3" },
            { id = 53310, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni01.mp3" },
            { id = 53311, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni02.mp3" },
            { id = 53312, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni03.mp3" },
            { id = 53313, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni04.mp3" },
            { id = 53314, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni05.mp3" },
            { id = 53315, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni06.mp3" },
            { id = 53316, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni07.mp3" },
            { id = 53317, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni08.mp3" },
            { id = 53318, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni10.mp3" },
            { id = 53319, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_IllidariWalkUni11.mp3" },
            { id = 53320, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_KaraborWalkUni01.mp3" },
            { id = 53321, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_KaraborWalkUni02.mp3" },
            { id = 53322, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_KaraborWalkUni03.mp3" },
            { id = 53323, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_KaraborWalkUni04.mp3" },
            { id = 53324, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_PreludeEvent01.mp3" },
            { id = 53325, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkHero01.mp3" },
            { id = 53326, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni02.mp3" },
            { id = 53327, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni03.mp3" },
            { id = 53328, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni04.mp3" },
            { id = 53329, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni05.mp3" },
            { id = 53330, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni06.mp3" },
            { id = 53331, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni07.mp3" },
            { id = 53332, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_ReliquaryWalkUni08.mp3" },
            { id = 53333, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkHero01.mp3" },
            { id = 53334, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni02.mp3" },
            { id = 53335, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni03.mp3" },
            { id = 53336, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni04.mp3" },
            { id = 53337, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni05.mp3" },
            { id = 53338, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni06.mp3" },
            { id = 53339, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni07.mp3" },
            { id = 53340, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SanctuaryWalkUni08.mp3" },
            { id = 53341, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_StormWalkHero02.mp3" },
            { id = 53342, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_StormWalkUni01.mp3" },
            { id = 53343, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_StormWalkUni03.mp3" },
            { id = 53344, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_StormWalkUni04.mp3" },
            { id = 53345, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SummitWalkUni01.mp3" },
            { id = 53346, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SummitWalkUni02.mp3" },
            { id = 53347, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SummitWalkUni03.mp3" },
            { id = 53348, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SummitWalkUni04.mp3" },
            { id = 53349, path = "Sound/music/ZONEMUSIC/BlackTemple/BT_SummitWalkUni05.mp3" },
        },
    },
}
